apiVersion: v1
kind: Service
metadata:
  name: service-ricplt-submgr-http
  namespace: ricplt
  labels:
    app: ricplt-submgr
    chart: submgr-3.0.0
    release: r4-submgr
    heritage: Helm
spec:
  type: ClusterIP
  selector:
    app: ricplt-submgr
    release: r4-submgr
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: http-compat
    port: 8088
    protocol: TCP
    targetPort: 8080
